### ISSUE TITLE
Try to stick to classes for styling

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/prioritiseMe#34]
The styles for this project have a mix of tag and class styling.

I would __really__ try to stick to just classes for styling. The trouble with adding styles for tags directly is that if you come back to a project, or add more features that re-use the same element types then you end up having to overwrite your old styles or accidentally passing styles to elements that you don't really want. It also gives your stylesheet clarity because everything can have appropriate naming.

Instead of:

```css
table {
  border-collapse: collapse;
  width: 90%;
  margin-left: 5%;
  margin-bottom: 5%;
}

table td, table th {
  border: 0.0625em solid #ddd;
  padding: 0.5em;
}
```

Do:

```css
.task-table {
  border-collapse: collapse;
  width: 90%;
  margin-left: 5%;
  margin-bottom: 5%;
}

.task-table__cell, .task-table__header-cell {
  border: 0.0625em solid #ddd;
  padding: 0.5em;
}
```

**Comment by SamiSha99** [comment]
I'm not sure when it comes to  as you need to add for

`.task-table__cell and 
.task-table__header-cell`

As in that case I would have to add for each single td and th a class.. or am I missing something?

**Comment by finnhodgkin** [comment]
Yeah you would, that's general good practice.

If you really want to then styling via the child selectors of named classes is still better than your current solution:

```css
.task-table {
  border-collapse: collapse;
  width: 90%;
  margin-left: 5%;
  margin-bottom: 5%;
}

.task-table td, .task-table th {
  border: 0.0625em solid #ddd;
  padding: 0.5em;
}
```
